#!/usr/bin/env python3
"""Generate disassembler tables: src/dasm_tables.s

Tables:
  dasm_mne[256]    — opcode → mnemonic index (1 byte each)
  dasm_mode[128]   — opcode → addressing mode (nybble-packed, 2 per byte)
  dasm_mne_lo[N]   — packed mnemonic strings, low byte (5-bit encoding)
  dasm_mne_hi[N]   — packed mnemonic strings, high byte
  dasm_mode_fmt[16]— mode format descriptors (1 byte each)
"""

import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from dev.instruction_set import OPCODES

# ── Invert OPCODES: opcode_byte → (mnemonic, mode) ──────────────
opc_map = {}
for mne, modes in OPCODES.items():
    for mode, opc in modes.items():
        opc_map[opc] = (mne.upper(), mode.upper())
for i in range(256):
    if i not in opc_map:
        opc_map[i] = ('???', 'IMP')

# ── Assign mnemonic indices (sorted) ────────────────────────────
mne_list = sorted(set(m for m, _ in opc_map.values()))
mne_idx = {m: i for i, m in enumerate(mne_list)}

# ── Mode encoding ───────────────────────────────────────────────
MODE_IDX = {
    'IMP':0, 'ACC':1, 'IMM':2, 'ZP':3, 'ZPX':4, 'ZPY':5,
    'ABS':6, 'ABX':7, 'ABY':8, 'IND':9, 'INX':10, 'INY':11,
    'REL':12, 'ZPI':13, 'AIX':14, 'ZPREL':15
}

# Mode format descriptors:
#   High nybble (left side):
#     0=nothing  1=$XX  2=$XXXX  3=#$XX  4=($XX  5=($XXXX
#     6=acc('a')  7=rel(computed $XXXX)  8=zprel($XX,$XXXX)
#   Low nybble (right side):
#     0=nothing  1=,x  2=,y  3=)  4=,x)  5=),y
MODE_FMT = {
    'IMP':  0x00, 'ACC':  0x60, 'IMM':  0x30,
    'ZP':   0x10, 'ZPX':  0x11, 'ZPY':  0x12,
    'ABS':  0x20, 'ABX':  0x21, 'ABY':  0x22,
    'IND':  0x53, 'INX':  0x44, 'INY':  0x45,
    'REL':  0x70, 'ZPI':  0x43, 'AIX':  0x54,
    'ZPREL':0x80,
}

# ── Pack mnemonic: 3 chars → 2 bytes (5 bits each) ─────────────
def pack_mne(s):
    def cv(c):
        if c == '?': return 27
        return ord(c) - ord('A') + 1
    v = (cv(s[0]) << 10) | (cv(s[1]) << 5) | cv(s[2])
    return v >> 8, v & 0xFF

# ── Build tables ────────────────────────────────────────────────
mne_tab = [mne_idx[opc_map[i][0]] for i in range(256)]
mode_tab = [MODE_IDX[opc_map[i][1]] for i in range(256)]
mode_packed = [(mode_tab[i] << 4) | mode_tab[i+1] for i in range(0, 256, 2)]
mne_packed = [pack_mne(m) for m in mne_list]
mode_fmt = [MODE_FMT[m] for m in ['IMP','ACC','IMM','ZP','ZPX','ZPY',
            'ABS','ABX','ABY','IND','INX','INY','REL','ZPI','AIX','ZPREL']]

# ── Emit assembly ──────────────────────────────────────────────
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   'src', 'dasm_tables.s')

with open(OUT, 'w') as f:
    f.write('; dasm_tables.s — generated by dev/dasm_tables.py — DO NOT EDIT\n')
    f.write(f'; {len(mne_list)} unique mnemonics, 256 opcodes\n\n')

    f.write('        .export dasm_mne_tab, dasm_mode_tab\n')
    f.write('        .export dasm_mne_lo, dasm_mne_hi\n')
    f.write('        .export dasm_mode_fmt\n\n')

    f.write('.segment "RODATA"\n\n')

    # mne_tab[256]
    f.write(f'; opcode → mnemonic index ({len(mne_list)} mnemonics)\n')
    f.write('dasm_mne_tab:\n')
    for row in range(16):
        vals = mne_tab[row*16:(row+1)*16]
        f.write(f'        .byte {",".join(f"${v:02X}" for v in vals)}')
        # Comment with hex range
        f.write(f'  ; ${row*16:02X}-${row*16+15:02X}\n')

    f.write(f'\n; opcode → addressing mode (nybble-packed, even=hi, odd=lo)\n')
    f.write('dasm_mode_tab:\n')
    for row in range(8):
        vals = mode_packed[row*16:(row+1)*16]
        f.write(f'        .byte {",".join(f"${v:02X}" for v in vals)}')
        f.write(f'  ; ${row*32:02X}-${row*32+31:02X}\n')

    f.write(f'\n; packed mnemonic strings (5-bit: A=1..Z=26, ?=27)\n')
    f.write('dasm_mne_lo:\n')
    f.write(f'        .byte {",".join(f"${lo:02X}" for _, lo in mne_packed)}\n')
    f.write('dasm_mne_hi:\n')
    f.write(f'        .byte {",".join(f"${hi:02X}" for hi, _ in mne_packed)}\n')

    f.write(f'\n; mode → format descriptor\n')
    f.write('; hi nybble: 0=none 1=$bb 2=$bbbb 3=#$bb 4=($bb 5=($bbbb 6=acc 7=rel 8=zprel\n')
    f.write('; lo nybble: 0=none 1=,x 2=,y 3=) 4=,x) 5=),y\n')
    f.write('dasm_mode_fmt:\n')
    names = ['IMP','ACC','IMM','ZP','ZPX','ZPY','ABS','ABX','ABY',
             'IND','INX','INY','REL','ZPI','AIX','ZPREL']
    f.write(f'        .byte {",".join(f"${v:02X}" for v in mode_fmt)}')
    f.write(f'  ; {",".join(names)}\n')

    # Comment: mnemonic index → name mapping
    f.write(f'\n; mnemonic index table ({len(mne_list)} entries):\n')
    for i, m in enumerate(mne_list):
        f.write(f';   {i:2d} = {m}\n')

# Size report
tbl_size = 256 + 128 + len(mne_list)*2 + 16
print(f'wrote {OUT}')
print(f'  {len(mne_list)} mnemonics, {tbl_size} bytes of tables')
print(f'    dasm_mne_tab:  256 bytes')
print(f'    dasm_mode_tab: 128 bytes')
print(f'    dasm_mne_lo:   {len(mne_list)} bytes')
print(f'    dasm_mne_hi:   {len(mne_list)} bytes')
print(f'    dasm_mode_fmt:  16 bytes')
