#!/usr/bin/env python3
"""
dev/dasm_tables.py — Generate disassembler table files for CSE.

Produces:
  src/dasm_tables.s    — packed mnemonic strings (RODATA)
  src/dasm_mne_idx.s   — MNE_xxx = N constants for dasm.s
"""

import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dev.instruction_set import OPCODES, MNEMONICS

SRC = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src')

# ── 65C02 additions not in instruction_set.py ────────────────────
CMOS_ADDITIONS = {
    0x80: ('BRA', 'REL'),
    0x04: ('TSB', 'ZP'),  0x0C: ('TSB', 'ABS'),
    0x14: ('TRB', 'ZP'),  0x1C: ('TRB', 'ABS'),
    0x64: ('STZ', 'ZP'),  0x74: ('STZ', 'ZPX'),
    0x9C: ('STZ', 'ABS'), 0x9E: ('STZ', 'ABX'),
    0x34: ('BIT', 'ZPX'), 0x3C: ('BIT', 'ABX'), 0x89: ('BIT', 'IMM'),
    0x7C: ('JMP', 'AIX'),
    0x1A: ('INC', 'ACC'), 0x3A: ('DEC', 'ACC'),
    0x5A: ('PHY', 'IMP'), 0x7A: ('PLY', 'IMP'),
    0xDA: ('PHX', 'IMP'), 0xFA: ('PLX', 'IMP'),
    0x12: ('ORA', 'ZPI'), 0x32: ('AND', 'ZPI'),
    0x52: ('EOR', 'ZPI'), 0x72: ('ADC', 'ZPI'),
    0x92: ('STA', 'ZPI'), 0xB2: ('LDA', 'ZPI'),
    0xD2: ('CMP', 'ZPI'), 0xF2: ('SBC', 'ZPI'),
}

# ── Collect all unique mnemonics ─────────────────────────────────
def collect_mnemonics():
    mne_set = {'???'}
    mne_set.update(['RMB', 'SMB', 'BBR', 'BBS'])   # base forms (digit appended by code)
    mne_set.update(['BRA', 'TRB', 'TSB'])           # CMOS not in OPCODES
    for mne in OPCODES:
        mne_set.add(mne)
    return sorted(mne_set)

MNE_LIST = collect_mnemonics()
MNE_IDX = {m: i for i, m in enumerate(MNE_LIST)}

# ── Pack 3-char mnemonic into 2 bytes (5 bits/char) ─────────────
def pack_mne(s):
    def cv(c):
        return 27 if c == '?' else ord(c) - ord('A') + 1
    s = s.upper().ljust(3, '?')[:3]
    v = (cv(s[0]) << 10) | (cv(s[1]) << 5) | cv(s[2])
    return v >> 8, v & 0xFF

# ── Write dasm_tables.s (packed strings) ─────────────────────────
with open(os.path.join(SRC, 'dasm_tables.s'), 'w') as f:
    f.write('; dasm_tables.s — GENERATED by dev/dasm_tables.py — DO NOT EDIT\n')
    f.write(f'; {len(MNE_LIST)} packed mnemonic strings ({len(MNE_LIST)*2} bytes)\n\n')
    f.write('.segment "RODATA"\n\n')
    f.write('        .export dasm_mne_str\n')
    f.write('dasm_mne_str:\n')
    for i, m in enumerate(MNE_LIST):
        hi, lo = pack_mne(m)
        f.write(f'        .byte ${hi:02X},${lo:02X}')
        f.write(f'         ; {i:2d} {m}\n')

# ── Write dasm_mne_idx.s (constants) ─────────────────────────────
with open(os.path.join(SRC, 'dasm_mne_idx.s'), 'w') as f:
    f.write('; dasm_mne_idx.s — GENERATED by dev/dasm_tables.py — DO NOT EDIT\n')
    f.write(f'; Mnemonic index constants for dasm.s ({len(MNE_LIST)} entries)\n\n')
    for m in MNE_LIST:
        name = 'UNK' if m == '???' else m
        f.write(f'MNE_{name:4s} = {MNE_IDX[m]}\n')

print(f'wrote dasm_tables.s: {len(MNE_LIST)} mnemonics, {len(MNE_LIST)*2} bytes')
print(f'wrote dasm_mne_idx.s: {len(MNE_LIST)} constants')
