; dasm.s — 6502/65C02/illegal opcode disassembler
;
; void dasm_insn(uint16_t addr)
;   Prints disassembled instruction at addr to current cursor position.
;   Uses io_putc for output.  Handles all 256 opcodes.
;
; Tables in dasm_tables.s (generated by dev/dasm_tables.py).

        .export _dasm_insn

        .import _io_putc
        .import dasm_mne_tab, dasm_mode_tab
        .import dasm_mne_lo, dasm_mne_hi
        .import dasm_mode_fmt

        .segment "ZEROPAGE"
_dasm_ptr: .res 2               ; pointer to instruction bytes
_dasm_tmp: .res 2               ; scratch for mnemonic unpacking / address computation
_dasm_opc: .res 1               ; saved opcode byte

        .segment "CODE"

; ── Entry: addr in A/X (lo/hi, __fastcall__) ────────────────────
_dasm_insn:
        sta _dasm_ptr
        stx _dasm_ptr+1

        ; ── Read opcode ─────────────────────────────────────────
        ldy #0
        lda (_dasm_ptr),y       ; A = opcode byte
        tax                     ; X = opcode (index for tables)

        ; ── Print mnemonic (3 chars, 5-bit packed) ──────────────
        stx _dasm_opc           ; save opcode for mode lookup later
        lda dasm_mne_tab,x      ; A = mnemonic index
        tay
        lda dasm_mne_hi,y       ; high byte of packed mnemonic
        sta _dasm_tmp
        lda dasm_mne_lo,y       ; low byte
        sta _dasm_tmp+1

        ; Unpack char 1: bits 14-10 = hi >> 2
        lda _dasm_tmp
        lsr
        lsr
        jsr @emit_char

        ; Unpack char 2: bits 9-5 = ((hi & 3) << 3) | (lo >> 5)
        lda _dasm_tmp+1         ; lo
        pha                     ; save lo for char 3
        lsr
        lsr
        lsr
        lsr
        lsr                     ; A = lo >> 5 (bits 7-5)
        pha                     ; save on stack
        lda _dasm_tmp           ; hi
        and #$03                ; bits 1-0
        asl
        asl
        asl                     ; << 3
        sta _dasm_tmp           ; reuse hi (done with it)
        pla                     ; lo >> 5
        ora _dasm_tmp           ; combine
        jsr @emit_char

        ; Unpack char 3: bits 4-0 = lo & $1F
        pla                     ; restore lo
        and #$1F
        jsr @emit_char

        ; ── Space after mnemonic ────────────────────────────────
        lda #$20                ; PETSCII space
        jsr _io_putc

        ; ── Get mode format descriptor ──────────────────────────
        ; Mode is nybble-packed: even opcodes in high nybble, odd in low
        lda _dasm_opc           ; restore opcode
        lsr                     ; A = opcode/2, carry = odd bit
        tay
        lda dasm_mode_tab,y
        bcc @even
        and #$0F                ; odd opcode: low nybble
        jmp @got_mode
@even:  lsr                     ; even opcode: shift high nybble down
        lsr
        lsr
        lsr
@got_mode:
        tay                     ; Y = mode index (0-15)
        lda dasm_mode_fmt,y     ; A = format descriptor

        ; ── Decode format descriptor ────────────────────────────
        ; High nybble = left side, Low nybble = right side
        pha                     ; save descriptor
        lsr
        lsr
        lsr
        lsr                     ; A = left type (0-8)

        cmp #0
        bne @not_imp
        pla                     ; discard saved descriptor
        rts                     ; IMP: nothing to print
@not_imp:
        cmp #6
        bne @not_acc
        jmp @do_acc             ; 6 = ACC
@not_acc:
        cmp #7
        bne @not_rel
        jmp @do_rel             ; 7 = REL
@not_rel:
        cmp #8
        bne @not_zprel
        jmp @do_zprel           ; 8 = ZPREL
@not_zprel:

        ; Types 1-5: optional prefix, then operand
        cmp #3
        bne @no_hash
        lda #$23                ; '#' PETSCII
        jsr _io_putc
        jmp @do_dollar
@no_hash:
        cmp #4
        bcc @do_dollar          ; 1,2: just '$'
        ; 4,5: '($'
        lda #$28                ; '(' PETSCII
        jsr _io_putc

@do_dollar:
        lda #$24                ; '$' PETSCII
        jsr _io_putc

        ; Check operand size: types 1,3,4 = 8-bit; types 2,5 = 16-bit
        pla                     ; restore descriptor
        pha                     ; save again for right side
        lsr
        lsr
        lsr
        lsr                     ; A = left type again
        cmp #2
        beq @op16
        cmp #5
        beq @op16

        ; 8-bit operand
        ldy #1
        lda (_dasm_ptr),y       ; operand byte
        jsr @print_hex2
        jmp @right_side

@op16:  ; 16-bit operand (little-endian: lo at +1, hi at +2)
        ldy #2
        lda (_dasm_ptr),y       ; high byte
        jsr @print_hex2
        ldy #1
        lda (_dasm_ptr),y       ; low byte
        jsr @print_hex2
        jmp @right_side

@do_acc:
        lda #$41                ; 'a' PETSCII
        jsr _io_putc
        jmp @right_side

@do_rel:
        ; Relative branch: compute target = addr + 2 + signed_offset
        lda #$24                ; '$'
        jsr _io_putc
        ldy #1
        lda (_dasm_ptr),y       ; signed offset
        ; Compute: _dasm_ptr + 2 + offset
        clc
        adc _dasm_ptr
        sta _dasm_tmp             ; target lo
        lda _dasm_ptr+1
        adc #0
        sta _dasm_tmp+1           ; tentative target hi (positive offset)
        ; Check if offset was negative (bit 7)
        ldy #1
        lda (_dasm_ptr),y
        bpl @rel_pos
        ; Negative offset: subtract 1 from high byte
        dec _dasm_tmp+1
@rel_pos:
        ; Add 2 for instruction length
        lda _dasm_tmp
        clc
        adc #2
        sta _dasm_tmp
        bcc @rel_print
        inc _dasm_tmp+1
@rel_print:
        lda _dasm_tmp+1
        jsr @print_hex2
        lda _dasm_tmp
        jsr @print_hex2
        jmp @right_side

@do_zprel:
        ; BBR/BBS: $XX,$XXXX (zp byte, then relative branch)
        lda #$24
        jsr _io_putc
        ldy #1
        lda (_dasm_ptr),y       ; ZP operand
        jsr @print_hex2
        lda #$2C                ; ','
        jsr _io_putc
        lda #$24                ; '$'
        jsr _io_putc
        ; Compute relative target = addr + 3 + signed_offset
        ldy #2
        lda (_dasm_ptr),y       ; signed offset (byte 3)
        clc
        adc _dasm_ptr
        sta _dasm_tmp
        lda _dasm_ptr+1
        adc #0
        sta _dasm_tmp+1
        ldy #2
        lda (_dasm_ptr),y
        bpl @zprel_pos
        dec _dasm_tmp+1
@zprel_pos:
        lda _dasm_tmp
        clc
        adc #3                  ; instruction is 3 bytes
        sta _dasm_tmp
        bcc @zprel_print
        inc _dasm_tmp+1
@zprel_print:
        lda _dasm_tmp+1
        jsr @print_hex2
        lda _dasm_tmp
        jsr @print_hex2
        ; fall through to right_side (no suffix for ZPREL)

        ; ── Right side (closing parens, index registers) ────────
@right_side:
        pla                     ; restore descriptor
        and #$0F                ; low nybble = right type
        beq @done               ; 0 = nothing

        cmp #1
        beq @do_cx              ; 1 = ,x
        cmp #2
        beq @do_cy              ; 2 = ,y
        cmp #3
        beq @do_cp              ; 3 = )
        cmp #4
        beq @do_cxp             ; 4 = ,x)
        ; 5 = ),y
        lda #$29                ; ')'
        jsr _io_putc
        lda #$2C                ; ','
        jsr _io_putc
        lda #$59                ; 'y' PETSCII
        jmp _io_putc            ; tail call

@do_cx: lda #$2C
        jsr _io_putc
        lda #$58                ; 'x' PETSCII
        jmp _io_putc

@do_cy: lda #$2C
        jsr _io_putc
        lda #$59                ; 'y' PETSCII
        jmp _io_putc

@do_cp: lda #$29                ; ')'
        jmp _io_putc

@do_cxp:
        lda #$2C
        jsr _io_putc
        lda #$58                ; 'x'
        jsr _io_putc
        lda #$29                ; ')'
        jmp _io_putc

@done:  rts

; ── Helpers ─────────────────────────────────────────────────────

; Print A as 2 hex digits via io_putc
@print_hex2:
        pha
        lsr
        lsr
        lsr
        lsr
        jsr @print_nybble
        pla
        and #$0F
@print_nybble:
        cmp #10
        bcc @digit
        adc #$36                ; 'a'-10-1 (carry is set) = $41-10 = PETSCII 'a'
        jmp _io_putc
@digit: adc #$30                ; '0' PETSCII (carry is clear)
        jmp _io_putc

; Emit 5-bit char value as PETSCII letter (1-26 → A-Z, 27 → '?')
@emit_char:
        and #$1F
        cmp #27
        bne @letter
        lda #$3F                ; '?' PETSCII
        jmp _io_putc
@letter:
        clc
        adc #$40                ; 1 → 'A' ($41), etc.
        jmp _io_putc
