; mn6_tables.s
; Generated by dev/mnemonic_tables.py – DO NOT EDIT BY HAND
;
; Per-mnemonic tables for the 6-bit legal-only NMOS mnemonic hash.
;   h6  = (c1*8 + c3*15 + T6[c2]) & $3F  (VICII screencodes A=1..Z=26)
;   fp  = (c1   + c2*218) & $FF
;
; mn6_fp[h]       8-bit fingerprint  (0 = empty slot)
; mn6_base_op[h]  base opcode
; mn6_profile[h]  bits7:6=cat(always 00 for mn6)  bit5=dir_bit  bits4:0=profile_index(0-29)
;
; 56/64 slots filled  (8 empty)
; 16 known false positives (0.09%) — see dev/mn6_fingerprint_collisions.txt

        .export mn6_fp
        .export mn6_base_op, mn6_profile

.segment "KDATA"

mn6_fp:
        .byte   $AC,$1C,$1B,$A3,$ED,$55,$3B,$A2  ; BIT  JMP  STX  CPX  AND  SEC  CLC  BPL
        .byte   $46,$15,$2F,$74,$D8,$46,$BE,$44  ; DEX  CMP  ASL  LDX  ROL  DEC  BVS  BEQ
        .byte   $48,$1B,$A3,$56,$55,$3B,$42,$46  ; PLA  STY  CPY  BRK  SED  CLD  TSX  DEY
        .byte   $14,$1A,$74,$EE,$E0,$84,$BE,$55  ; BMI  RTI  LDY  BNE  PHP  TXA  BVC  SEI
        .byte   $3B,$C7,$00,$3B,$EE,$63,$D8,$00  ; CLI  SBC  ---  CLV  TAX  ORA  ROR  ---
        .byte   $D4,$1B,$00,$84,$38,$90,$00,$1A  ; NOP  STA  ---  TXS  JSR  BCS  ---  RTS
        .byte   $F5,$48,$74,$EE,$5E,$F5,$00,$00  ; INX  PLP  LDA  TAY  TYA  INC  ---  ---
        .byte   $69,$00,$00,$E0,$3A,$90,$CB,$F5  ; ADC  ---  ---  PHA  LSR  BCC  EOR  INY

mn6_base_op:
        .byte   $20,$4C,$82,$E0,$21,$38,$18,$10  ; BIT  JMP  STX  CPX  AND  SEC  CLC  BPL
        .byte   $CA,$C1,$02,$A2,$22,$C2,$70,$F0  ; DEX  CMP  ASL  LDX  ROL  DEC  BVS  BEQ
        .byte   $68,$80,$C0,$00,$F8,$D8,$BA,$88  ; PLA  STY  CPY  BRK  SED  CLD  TSX  DEY
        .byte   $30,$40,$A0,$D0,$08,$8A,$50,$78  ; BMI  RTI  LDY  BNE  PHP  TXA  BVC  SEI
        .byte   $58,$E1,$00,$B8,$AA,$01,$62,$00  ; CLI  SBC  ---  CLV  TAX  ORA  ROR  ---
        .byte   $EA,$81,$00,$9A,$20,$B0,$00,$60  ; NOP  STA  ---  TXS  JSR  BCS  ---  RTS
        .byte   $E8,$28,$A1,$A8,$98,$E2,$00,$00  ; INX  PLP  LDA  TAY  TYA  INC  ---  ---
        .byte   $61,$00,$00,$48,$42,$90,$41,$C8  ; ADC  ---  ---  PHA  LSR  BCC  EOR  INY

mn6_profile:
        .byte   $4C,$4E,$11,$15,$46,$00,$00,$01  ; BIT  JMP  STX  CPX  AND  SEC  CLC  BPL
        .byte   $00,$46,$0B,$10,$0B,$4A,$01,$01  ; DEX  CMP  ASL  LDX  ROL  DEC  BVS  BEQ
        .byte   $00,$14,$15,$00,$00,$00,$00,$00  ; PLA  STY  CPY  BRK  SED  CLD  TSX  DEY
        .byte   $01,$00,$0D,$01,$00,$00,$01,$00  ; BMI  RTI  LDY  BNE  PHP  TXA  BVC  SEI
        .byte   $00,$46,$00,$00,$00,$46,$0B,$00  ; CLI  SBC  ---  CLV  TAX  ORA  ROR  ---
        .byte   $00,$48,$00,$00,$05,$01,$00,$00  ; NOP  STA  ---  TXS  JSR  BCS  ---  RTS
        .byte   $00,$00,$46,$00,$00,$4A,$00,$00  ; INX  PLP  LDA  TAY  TYA  INC  ---  ---
        .byte   $46,$00,$00,$00,$0B,$01,$46,$00  ; ADC  ---  ---  PHA  LSR  BCC  EOR  INY

