; mn7_tables.s
; Generated by dev/mnemonic_tables.py – DO NOT EDIT BY HAND
;
; Per-mnemonic tables for the 7-bit full-114-mnemonic hash.
;   h7  = (c1*4 + c3*1 + T7[c2]) & $7F  (VICII screencodes A=1..Z=26)
;   fp  = (c2<<3) | (c3>>2)
;
; mn7_fp[h]       8-bit fingerprint  (0 = empty slot; fp ≥ 8 always)
; mn7_base_op[h]  base opcode  (semantics identical to mn_config.s)
; mn7_profile[h]  bits7:6=cat(00=legal 01=legal+CMOS 10=illegal 11=CMOS-only)
;                 bit5=dir_bit, bits4:0=profile_index(0-29)
;
; 114/128 slots filled  (14 empty)
; 0 false positives — see dev/hashes.py mn7.verify_fingerprint()

        .export mn7_fp
        .export mn7_base_op, mn7_profile

.segment "RODATA"

mn7_fp:
        .byte   $7B,$C0,$08,$91,$90,$6C,$7C,$00  ; ROL  TXA  AAC  SRE  TRB  CMP  ROR  ---
        .byte   $00,$B0,$60,$61,$7C,$00,$00,$9B  ; ---  BVC  CLC  CLD  TOP  ---  ---  ASL
        .byte   $62,$64,$9B,$C4,$A0,$9C,$20,$0E  ; CLI  ALR  ASO  TXS  STA  ASR  ADC  AAX
        .byte   $A2,$B4,$70,$71,$71,$65,$28,$29  ; RTI  BVS  ANC  AND  ANE  CLV  SEC  SED
        .byte   $71,$6C,$A4,$C8,$2A,$98,$98,$C8  ; BNE  JMP  RTS  SYA  SEI  ISB  ISC  TYA
        .byte   $00,$46,$10,$A6,$A6,$A6,$4B,$65  ; ---  AHX  SBC  STX  STY  STZ  CIM  HLT
        .byte   $0B,$4D,$3B,$68,$99,$C0,$00,$68  ; JAM  BIT  IGN  RMB  LSE  AXA  ---  SMB
        .byte   $00,$9C,$70,$90,$60,$0C,$0C,$16  ; ---  JSR  INC  BRA  PLA  LAR  LAS  SBX
        .byte   $20,$9C,$00,$0E,$60,$92,$00,$C4  ; LDA  LSR  ---  LAX  RLA  BRK  ---  AXS
        .byte   $94,$58,$74,$64,$7C,$4B,$40,$76  ; ARR  SKB  INS  PLP  DOP  KIL  PHA  INX
        .byte   $76,$98,$7C,$66,$66,$98,$63,$26  ; INY  TSB  EOR  PLX  PLY  USB  SLO  LDX
        .byte   $26,$83,$40,$18,$08,$44,$0C,$0E  ; LDY  BPL  SHA  BCC  XAA  PHP  TAS  SAX
        .byte   $0E,$C0,$28,$0E,$0E,$46,$46,$9E  ; SAY  LXA  DEC  TAX  TAY  PHX  PHY  TSX
        .byte   $2C,$86,$86,$1C,$44,$1B,$0C,$90  ; BEQ  CPX  CPY  BCS  SHS  DCM  XAS  ORA
        .byte   $1C,$46,$46,$00,$7C,$14,$14,$2E  ; DCP  SHX  SHY  ---  NOP  BBR  BBS  DEX
        .byte   $2E,$00,$6A,$90,$00,$C0,$00,$00  ; DEY  ---  BMI  RRA  ---  SXA  ---  ---

mn7_base_op:
        .byte   $22,$8A,$2B,$43,$14,$C1,$62,$00  ; ROL  TXA  AAC  SRE  TRB  CMP  ROR  ---
        .byte   $00,$50,$18,$D8,$00,$00,$00,$02  ; ---  BVC  CLC  CLD  TOP  ---  ---  ASL
        .byte   $58,$4B,$03,$9A,$81,$4B,$61,$83  ; CLI  ALR  ASO  TXS  STA  ASR  ADC  AAX
        .byte   $40,$70,$0B,$21,$8B,$B8,$38,$F8  ; RTI  BVS  ANC  AND  ANE  CLV  SEC  SED
        .byte   $D0,$4C,$60,$80,$78,$E3,$E3,$98  ; BNE  JMP  RTS  SYA  SEI  ISB  ISC  TYA
        .byte   $00,$9F,$E1,$82,$80,$00,$D2,$02  ; ---  AHX  SBC  STX  STY  STZ  CIM  HLT
        .byte   $02,$20,$00,$07,$43,$83,$00,$87  ; JAM  BIT  IGN  RMB  LSE  AXA  ---  SMB
        .byte   $00,$20,$E2,$80,$68,$A3,$A3,$CB  ; ---  JSR  INC  BRA  PLA  LAR  LAS  SBX
        .byte   $A1,$42,$00,$A3,$23,$00,$00,$CB  ; LDA  LSR  ---  LAX  RLA  BRK  ---  AXS
        .byte   $6B,$80,$E3,$28,$00,$02,$48,$E8  ; ARR  SKB  INS  PLP  DOP  KIL  PHA  INX
        .byte   $C8,$04,$41,$FA,$7A,$EB,$03,$A2  ; INY  TSB  EOR  PLX  PLY  USB  SLO  LDX
        .byte   $A0,$10,$83,$90,$8B,$08,$83,$83  ; LDY  BPL  SHA  BCC  XAA  PHP  TAS  SAX
        .byte   $80,$AB,$C2,$AA,$A8,$DA,$5A,$BA  ; SAY  LXA  DEC  TAX  TAY  PHX  PHY  TSX
        .byte   $F0,$E0,$C0,$B0,$83,$C3,$83,$01  ; BEQ  CPX  CPY  BCS  SHS  DCM  XAS  ORA
        .byte   $C3,$82,$80,$00,$EA,$0F,$8F,$CA  ; DCP  SHX  SHY  ---  NOP  BBR  BBS  DEX
        .byte   $88,$00,$30,$63,$00,$82,$00,$00  ; DEY  ---  BMI  RRA  ---  SXA  ---  ---

mn7_profile:
        .byte   $0B,$00,$82,$9B,$DD,$46,$0B,$00  ; ROL  TXA  AAC  SRE  TRB  CMP  ROR  ---
        .byte   $00,$01,$00,$00,$96,$00,$00,$0B  ; ---  BVC  CLC  CLD  TOP  ---  ---  ASL
        .byte   $00,$82,$9B,$00,$48,$82,$46,$93  ; CLI  ALR  ASO  TXS  STA  ASR  ADC  AAX
        .byte   $00,$01,$82,$46,$82,$00,$00,$00  ; RTI  BVS  ANC  AND  ANE  CLV  SEC  SED
        .byte   $01,$4E,$00,$9A,$00,$9B,$9B,$00  ; BNE  JMP  RTS  SYA  SEI  ISB  ISC  TYA
        .byte   $00,$99,$46,$11,$14,$FC,$80,$80  ; ---  AHX  SBC  STX  STY  STZ  CIM  HLT
        .byte   $80,$4C,$9C,$C3,$9B,$98,$00,$C3  ; JAM  BIT  IGN  RMB  LSE  AXA  ---  SMB
        .byte   $00,$05,$4A,$C1,$00,$99,$99,$82  ; ---  JSR  INC  BRA  PLA  LAR  LAS  SBX
        .byte   $46,$0B,$00,$92,$9B,$00,$00,$82  ; LDA  LSR  ---  LAX  RLA  BRK  ---  AXS
        .byte   $82,$82,$9B,$00,$97,$80,$00,$00  ; ARR  SKB  INS  PLP  DOP  KIL  PHA  INX
        .byte   $00,$DD,$46,$C0,$C0,$82,$9B,$10  ; INY  TSB  EOR  PLX  PLY  USB  SLO  LDX
        .byte   $0D,$01,$98,$01,$82,$00,$99,$93  ; LDY  BPL  SHA  BCC  XAA  PHP  TAS  SAX
        .byte   $9A,$82,$4A,$00,$00,$C0,$C0,$00  ; SAY  LXA  DEC  TAX  TAY  PHX  PHY  TSX
        .byte   $01,$15,$15,$01,$99,$9B,$99,$46  ; BEQ  CPX  CPY  BCS  SHS  DCM  XAS  ORA
        .byte   $9B,$99,$9A,$00,$00,$C4,$C4,$00  ; DCP  SHX  SHY  ---  NOP  BBR  BBS  DEX
        .byte   $00,$00,$01,$9B,$00,$99,$00,$00  ; DEY  ---  BMI  RRA  ---  SXA  ---  ---

