; mn_asm_tables.s
; Generated by dev/mnemonic_tables.py – DO NOT EDIT BY HAND
;
; mode_offset      64 bytes  – 4 zones × 16 modes; byte = bbb<<2 to OR
;                             into base_op; $FF = invalid/exception
;                             zones: cc=00 [0..15], cc=01 [16..31], cc=10 [32..47], cc=11 [48..63]
; direct_opcodes   16 bytes  – direct opcode per mode for dir_bit profiles
;                             profile 28 (STZ) at offset 0  (FIRST_DIR_PROFILE=28)
;
        .export mode_offset, direct_opcodes
        .export FIRST_DIR_PROFILE

.segment "RODATA"

mode_offset:
; cc=00
        .byte   $FF,$FF,$00,$04,$14,$FF,$0C,$1C      ; IMP  ACC  IMM  ZP  ZPX  ZPY  ABS  ABX
        .byte   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF      ; ABY  IND  INX  INY  REL  ZPI  AIX  ZPR

; cc=01
        .byte   $FF,$FF,$08,$04,$14,$FF,$0C,$1C      ; IMP  ACC  IMM  ZP  ZPX  ZPY  ABS  ABX
        .byte   $18,$FF,$00,$10,$FF,$FF,$FF,$FF      ; ABY  IND  INX  INY  REL  ZPI  AIX  ZPR

; cc=10
        .byte   $FF,$08,$00,$04,$14,$14,$0C,$1C      ; IMP  ACC  IMM  ZP  ZPX  ZPY  ABS  ABX
        .byte   $1C,$FF,$FF,$FF,$FF,$FF,$FF,$FF      ; ABY  IND  INX  INY  REL  ZPI  AIX  ZPR

; cc=11 (illegal NMOS)
        .byte   $FF,$FF,$FF,$04,$14,$14,$0C,$1C      ; IMP  ACC  IMM  ZP  ZPX  ZPY  ABS  ABX
        .byte   $FF,$FF,$00,$10,$FF,$FF,$FF,$FF      ; ABY  IND  INX  INY  REL  ZPI  AIX  ZPR
        ; NOTE: ABY=$FF — genuine bbb conflict (bbb=6 vs bbb=7).
        ;   All zone=3/ABY handled by runtime exception in opcode_lookup.s

FIRST_DIR_PROFILE = 28
direct_opcodes:
; profile 28 (STZ)
        .byte   $00,$00,$00,$64,$74,$00,$9C,$9E      ; IMP  ACC  IMM  ZP  ZPX  ZPY  ABS  ABX
        .byte   $00,$00,$00,$00,$00,$00,$00,$00      ; ABY  IND  INX  INY  REL  ZPI  AIX  ZPR

