; mn_config.s
; Generated by dev/mnemonic_tables.py – DO NOT EDIT BY HAND
;
; Per-mnemonic config tables indexed by 7-bit hash h7.
;   h7 = (c1*4 + c3 + HASH_T[c2]) & $7F   (VICII screencodes A=1..Z=26)
;
; mn_base_op[h]  base opcode for the mnemonic at hash slot h
; mn_profile[h]  operand profile index (0–29); bits 7:5 = 0
;
; Base-opcode semantics by zone:
;   idx 0–5   Zone A–F: base IS the final opcode.
;             Zone D (idx=3): emit base|(bit<<4); 1-byte ZP addr.
;             Zone E (idx=4): emit base|(bit<<4); ZP addr + rel.
;   idx 6–29  Zone G/H: opcode = base | (bbb<<2), bbb = f(mode).
;             JMP: IND = base|$20, AIX = base|$30.
;             STZ: split aaa; needs per-mode opcode table.
;
; 114/128 slots filled

.segment "RODATA"

mn_base_op:
        .byte   $22,$8A,$2B,$43,$00,$C1,$62,$00  ; ROL  TXA  AAC  SRE  TRB  CMP  ROR  ---
        .byte   $00,$50,$18,$D8,$00,$00,$00,$02  ; ---  BVC  CLC  CLD  TOP  ---  ---  ASL
        .byte   $58,$4B,$03,$9A,$81,$4B,$61,$83  ; CLI  ALR  ASO  TXS  STA  ASR  ADC  AAX
        .byte   $40,$70,$0B,$21,$8B,$B8,$38,$F8  ; RTI  BVS  ANC  AND  ANE  CLV  SEC  SED
        .byte   $D0,$4C,$60,$80,$78,$E3,$E3,$98  ; BNE  JMP  RTS  SYA  SEI  ISB  ISC  TYA
        .byte   $00,$83,$E1,$82,$80,$00,$D2,$02  ; ---  AHX  SBC  STX  STY  STZ  CIM  HLT
        .byte   $02,$20,$00,$07,$43,$83,$00,$87  ; JAM  BIT  IGN  RMB  LSE  AXA  ---  SMB
        .byte   $00,$20,$E2,$80,$68,$A3,$A3,$CB  ; ---  JSR  INC  BRA  PLA  LAR  LAS  SBX
        .byte   $A1,$42,$00,$A3,$23,$00,$00,$CB  ; LDA  LSR  ---  LAX  RLA  BRK  ---  AXS
        .byte   $6B,$80,$E3,$28,$00,$02,$48,$E8  ; ARR  SKB  INS  PLP  DOP  KIL  PHA  INX
        .byte   $C8,$00,$41,$FA,$7A,$EB,$03,$A2  ; INY  TSB  EOR  PLX  PLY  USB  SLO  LDX
        .byte   $A0,$10,$83,$90,$8B,$08,$83,$83  ; LDY  BPL  SHA  BCC  XAA  PHP  TAS  SAX
        .byte   $80,$AB,$C2,$AA,$A8,$DA,$5A,$BA  ; SAY  LXA  DEC  TAX  TAY  PHX  PHY  TSX
        .byte   $F0,$E0,$C0,$B0,$83,$C3,$83,$01  ; BEQ  CPX  CPY  BCS  SHS  DCM  XAS  ORA
        .byte   $C3,$82,$80,$00,$EA,$0F,$8F,$CA  ; DCP  SHX  SHY  ---  NOP  BBR  BBS  DEX
        .byte   $88,$00,$30,$63,$00,$82,$00,$00  ; DEY  ---  BMI  RRA  ---  SXA  ---  ---

mn_profile:
        .byte   $0B,$00,$02,$1B,$1D,$06,$0B,$00  ; ROL  TXA  AAC  SRE  TRB  CMP  ROR  ---
        .byte   $00,$01,$00,$00,$16,$00,$00,$0B  ; ---  BVC  CLC  CLD  TOP  ---  ---  ASL
        .byte   $00,$02,$1B,$00,$08,$02,$06,$13  ; CLI  ALR  ASO  TXS  STA  ASR  ADC  AAX
        .byte   $00,$01,$02,$06,$02,$00,$00,$00  ; RTI  BVS  ANC  AND  ANE  CLV  SEC  SED
        .byte   $01,$0E,$00,$1A,$00,$1B,$1B,$00  ; BNE  JMP  RTS  SYA  SEI  ISB  ISC  TYA
        .byte   $00,$19,$06,$11,$14,$1C,$00,$00  ; ---  AHX  SBC  STX  STY  STZ  CIM  HLT
        .byte   $00,$0C,$1C,$03,$1B,$18,$00,$03  ; JAM  BIT  IGN  RMB  LSE  AXA  ---  SMB
        .byte   $00,$05,$0A,$01,$00,$19,$19,$02  ; ---  JSR  INC  BRA  PLA  LAR  LAS  SBX
        .byte   $06,$0B,$00,$12,$1B,$00,$00,$02  ; LDA  LSR  ---  LAX  RLA  BRK  ---  AXS
        .byte   $02,$02,$1B,$00,$17,$00,$00,$00  ; ARR  SKB  INS  PLP  DOP  KIL  PHA  INX
        .byte   $00,$1D,$06,$00,$00,$02,$1B,$10  ; INY  TSB  EOR  PLX  PLY  USB  SLO  LDX
        .byte   $0D,$01,$18,$01,$02,$00,$19,$13  ; LDY  BPL  SHA  BCC  XAA  PHP  TAS  SAX
        .byte   $1A,$02,$0A,$00,$00,$00,$00,$00  ; SAY  LXA  DEC  TAX  TAY  PHX  PHY  TSX
        .byte   $01,$15,$15,$01,$19,$1B,$19,$06  ; BEQ  CPX  CPY  BCS  SHS  DCM  XAS  ORA
        .byte   $1B,$19,$1A,$00,$00,$04,$04,$00  ; DCP  SHX  SHY  ---  NOP  BBR  BBS  DEX
        .byte   $00,$00,$01,$1B,$00,$19,$00,$00  ; DEY  ---  BMI  RRA  ---  SXA  ---  ---

