; mn_modes.s
; Generated by dev/mnemonic_tables.py – DO NOT EDIT BY HAND
;
; Operand profile addressing-mode bitfield table.  30 profiles × 2 bytes = 60 bytes.
; Indexed by the 5-bit operand profile field in the per-mnemonic config table (0..29).
;
; Index zones (see dev/instruction_set.py for full assembler dispatch map):
;   idx = 0        IMP: no operand
;   idx = 1        REL: 1-byte relative
;   idx = 2        IMM: 1-byte immediate
;   idx = 3        ZP:  leading bit(0-7) operand → opcode; 1-byte ZP addr
;   idx = 4        ZPREL: leading bit(0-7) operand → opcode; ZP + rel
;   idx = 5        ABS: 2-byte absolute  (JSR only)
;   idx = 0..5     opcode fixed by mnemonic; no mode disambiguation
;   idx = 6..15    NMOS/CMOS pairs: even=NMOS, odd=CMOS
;                  if (idx & 1 == 0) and cpu==65C02: use idx+1
;   idx = 16..29   standalone multi-mode, no CMOS upgrade
;                  27=profile 8 bits  28=profile 10 bits  29=profile 12 bits (Zone G overflow)
;   mn_modes_lo  bits 0-7 : IMP ACC IMM ZP ZPX ZPY ABS ABX
;   mn_modes_hi  bits 0-7 : ABY IND INX INY REL ZPI AIX ZPREL
; A set bit means that addressing mode is supported by this profile.

        .export mn_modes_lo, mn_modes_hi

.segment "RODATA"

mn_modes_lo:
        .byte   $01,$00,$04,$08          ; 0  1  2  3
        .byte   $00,$40,$DC,$DC          ; 4  5  6  7
        .byte   $D8,$D8,$D8,$DA          ; 8  9  10  11
        .byte   $48,$DC,$40,$40          ; 12  13  14  15
        .byte   $6C,$68,$68,$68          ; 16  17  18  19
        .byte   $58,$4C,$C0,$18          ; 20  21  22  23
        .byte   $00,$00,$80,$D8          ; 24  25  26  27
        .byte   $D8,$48                  ; 28  29

mn_modes_hi:
        .byte   $00,$10,$00,$00          ; 0  1  2  3
        .byte   $80,$00,$0D,$2D          ; 4  5  6  7
        .byte   $0D,$2D,$00,$00          ; 8  9  10  11
        .byte   $00,$00,$02,$42          ; 12  13  14  15
        .byte   $01,$00,$0D,$04          ; 16  17  18  19
        .byte   $00,$00,$00,$00          ; 20  21  22  23
        .byte   $09,$01,$00,$0D          ; 24  25  26  27
        .byte   $00,$00                  ; 28  29

