; oplen_tbl.s — packed opcode→instruction length table
; Generated by dev/mnemonic_tables.py — DO NOT EDIT BY HAND
;
; 64 bytes: 256 opcodes × 2 bits.  4 entries per byte.
; Packing: byte = opcode >> 2.  Position = opcode & 3.
;   pos 0 = bits 1:0, pos 1 = bits 3:2,
;   pos 2 = bits 5:4, pos 3 = bits 7:6.
; Values: 1 = 1 byte, 2 = 2 bytes, 3 = 3 bytes.
; Safe for all CPU modes (65C02 superset).

        .export oplen_tbl

.segment "RODATA"

oplen_tbl:
        .byte $99,$AA,$99,$FF,$AA,$AA,$DD,$FF  ; $00-$1F
        .byte $9B,$AA,$99,$FF,$AA,$AA,$DD,$FF  ; $20-$3F
        .byte $99,$A9,$99,$FF,$AA,$A9,$DD,$FD  ; $40-$5F
        .byte $99,$AA,$99,$FF,$AA,$AA,$DD,$FF  ; $60-$7F
        .byte $9A,$AA,$99,$FF,$AA,$AA,$DD,$FF  ; $80-$9F
        .byte $AA,$AA,$99,$FF,$AA,$AA,$DD,$FF  ; $A0-$BF
        .byte $9A,$AA,$99,$FF,$9A,$A9,$DD,$FD  ; $C0-$DF
        .byte $9A,$AA,$99,$FF,$AA,$A9,$DD,$FD  ; $E0-$FF

